### ISSUE TITLE
Has this been tested?

### ISSUE THREAD

**Issue by frillweeman** [jimilinuxguy/flipperzero-touchtunes#14]
I've tried this several times at about 10 different bars over the last year. I bought a TouchTunes remote off eBay, and the remote works every time. Most are set to 000 except in places with multiple jukeboxes. For some reason, I've never gotten these files to actually do anything to the jukebox even when the remote works. Is there something I'm missing? Potentially a range issue?

**Comment by jimilinuxguy** [comment]
I am not sure what the issue is. If you are sure the code is 000 then you could/should pick a file that has the 000 pattern in it and test. You should be on 433.92 mhz.

**Comment by frillweeman** [comment]
Ok, I'll try again and report back if I notice any issues.
